# Generated by Django 4.1.7 on 2023-03-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(null=True, upload_to="profile_pics"),
        ),
    ]
